<?php

/**
 * Implementation of hook_menu
 */
function custom_quiz_menu(){
    $items = array();
	$items['quiz'] = array(
	   'title' => 'Quiz',
	   'page callback' => 'custom_quiz_page',
	   'access callback' => 'user_is_logged_in',
	   'type' => MENU_CALLBACK
	); 
  return $items;	
} 

/**
 * Page Callback
 */
function custom_quiz_page(){
 global $user;
   drupal_add_js(drupal_get_path('module', 'custom_quiz') . '/js/custom.quiz.js');
   $html  = '<div id="quiz-frame">';
   $html .= '<iframe id="frame-wide" src="http://volunteer.iamin.in/iframe-quiz/quiz-result?member_id='.$user->uid.'" style="width:100%;height:100%" scrolling="no"></iframe>';
   $html .= '<iframe id="frame-narrow" src="http://volunteer.iamin.in/iframe-quiz-mobile/m-quiz-result?member_id='.$user->uid.'" scrolling="auto" style="width:100%;height:100%;display:none;" scrolling="no"></iframe>';
   $html .= '</div>';
  return $html;  
}

/**
 * Implementation of hook_block_info().
 */
function custom_quiz_block_info(){
    $blocks = array();
	$blocks['dna_quiz'] = array('info'  => t('DNA Quiz'),'cache' => DRUPAL_NO_CACHE,);
   return $blocks;	
} 

/**
 * Implementation of hook_block_view().
 */
function custom_quiz_block_view($delta=''){
  global $user;
    $block = array();
	switch($delta){
		case 'dna_quiz':
			//$block['subject'] = t('DNA Quiz');
			$access = volunteer_badge($user->uid, TRUE);
			$access = ($access->status == 'sucess')?FALSE:TRUE;
			//$block['content'] = array('#markup' => custom_quiz_markup(), '#access' =>  custom_quiz_access_callback());
			$block['content'] = array('#markup' => custom_quiz_markup(), '#access' =>  $access);
		break;
	}
   return $block;	
}

/**
 * Block Text
 */
function custom_quiz_markup(){
  global $language;
  
  if($language->language == 'en'){
	   if(user_is_anonymous())
	  $link = l(t('<img src="http://www.iamin.in/sites/all/themes/project2welve/images/take-quiz-english.png">'), 'ajax_register/login/nojs', array('attributes' => array('class' => array('ctools-use-modal', 'ctools-modal-ctools-ajax-register-style', 'submit', 'button')),'html' => true, 'query' => array('destination' => 'quiz')));
	else
    $link = l(t('<img src="http://www.iamin.in/sites/all/themes/project2welve/images/take-quiz-english.png">'), 'quiz', array('attributes' => array('class' => array('submit', 'button')), 'html' => true));
	}  
  if($language->language == 'hi'){
    if(user_is_anonymous())
	  $link = l(t('<img src="http://www.iamin.in/sites/all/themes/project2welve/images/take-quiz-hindi.png">'), 'ajax_register/login/nojs', array('attributes' => array('class' => array('ctools-use-modal', 'ctools-modal-ctools-ajax-register-style', 'submit', 'button')),'html' => true, 'query' => array('destination' => 'quiz')));
	else
    $link = l(t('<img src="http://www.iamin.in/sites/all/themes/project2welve/images/take-quiz-hindi.png">'), 'quiz', array('attributes' => array('class' => array('submit', 'button')), 'html' => true));
  }
    $html  = '<div class="markup-wrapper">';
	/*$html .=    '<div class="text first">'. t('Are you') . '</div>';
	$html .=    '<div class="text">'. t('NETA MATERIAL') . '</div>';
	if($language->language == 'en'){
	  $html .=    '<div class="text">'. t('or') . '</div>';
	}  
	$html .=    '<div class="text">'. t('BOL BACHCHAN') . '</div>';
	$html .=    '<div class="link">'. $link . t('your Citizen DNA.') . '</div>';*/
	$html .=    '<div class="text">'. $link . '</div>';
	$html .= '</div>';
  return $html;	
}

/**
 * Quiz Block Access
 */
function  custom_quiz_access_callback(){
    global $user;
	$access = TRUE;
	if($user->uid != 0){
	    $query = 'SELECT uid FROM users_quiz_result WHERE uid = :uid LIMIT 1';
		$result = db_query($query, array(':uid' => $user->uid));
		if($result->rowCount() > 0) { $access = FALSE; }
	}			
  return $access;	
}
